package com.anonforge.domain.model

import kotlinx.datetime.Instant

/**
 * Domain model for a virtual phone number alias.
 *
 * MANUAL INPUT MODE: User obtains numbers from external services
 * (Hushed, OnOff, TextNow) and saves them here for reuse.
 *
 * Security: Stored encrypted in local database (SQLCipher).
 *
 * @property id Unique identifier (auto-generated by Room)
 * @property phoneNumber The virtual phone number (E.164 format recommended)
 * @property friendlyName User-defined label (e.g., "Hushed", "OnOff work")
 * @property isPrimary True if this is the default number for new identities
 * @property usageCount Number of times this alias has been used
 * @property createdAt Timestamp when the alias was added
 * @property lastUsedAt Timestamp of last usage (null if never used)
 */
data class PhoneAlias(
    val id: Long = 0,
    val phoneNumber: String,
    val friendlyName: String = "",
    val isPrimary: Boolean = false,
    val usageCount: Int = 0,
    val createdAt: Instant,
    val lastUsedAt: Instant? = null
) {
    /**
     * Display-friendly format for UI lists.
     * Shows "Name (Number)" if name exists, otherwise just the number.
     */
    @Suppress("unused") // Public API for phone alias list UI display
    val displayFormat: String
        get() = if (friendlyName.isNotBlank()) "$friendlyName ($phoneNumber)" else phoneNumber
}